-- VIN Gallery database setup for Supabase
create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  vin text unique not null check (char_length(vin)=17),
  year int,
  make text,
  model text,
  description text,
  created_at timestamptz default now()
);

create table if not exists public.vehicle_photos (
  id bigint generated by default as identity primary key,
  vin text not null references public.vehicles(vin) on delete cascade,
  public_url text not null,
  storage_path text,
  created_at timestamptz default now()
);

alter table public.vehicles enable row level security;
alter table public.vehicle_photos enable row level security;

create policy "public can read vehicles"
on public.vehicles for select using (true);

create policy "public can read photos"
on public.vehicle_photos for select using (true);

-- Storage bucket
insert into storage.buckets (id,name,public)
values ('vehicle-photos','vehicle-photos',true)
on conflict (id) do nothing;

-- For a private production admin, use Supabase Auth and replace these upload policies
-- with authenticated-only policies. This starter leaves storage upload policy to be
-- configured in the dashboard, so you don't accidentally expose unrestricted uploads.
